### ISSUE TITLE
Error on redirect page

### ISSUE THREAD

**Issue by donleo123** [coingate/prestashop-plugin#8]
(1/1) ContextErrorExceptionWarning: A non-numeric value encountered
--
in redirect.php line 119
at CoingateRedirectModuleFrontController->generateToken(1)in redirect.php line 51
at CoingateRedirectModuleFrontController->initContent()in Controller.php line 281
at ControllerCore->run()in Dispatcher.php line 511
at DispatcherCore->dispatch()in index.php line 28

Got this error when checking out:
http://prntscr.com/mz71i5
Sandbox enabled

**Comment by donleo123** [comment]
Same error when sandbox is disabled

**Comment by vgumonis** [comment]
Hi, 

We recently addressed this issue in our newest release, that improves compatibility with newer prestashop and php versions. 

To fix this issue please update to our newest release. However because our newest update is, at the moment, not live in the prestashop marketplace, please use our Github release
